=== consultant-1379/pathfinding-1/symboliclinkcreator/conf/eniqmifconfig.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--DTD generated by XMLSpy v2007 sp1 (http://www.altova.com)-->
<!ELEMENT subdir (#PCDATA)>
<!ELEMENT nodeTypeDir (#PCDATA)>
<!ELEMENT neType (#PCDATA)>
<!ELEMENT maxNumLinks (#PCDATA)>
<!ELEMENT InterfaceData ((Interface+))>
<!ELEMENT Interface ((neType, maxNumLinks, nodeTypeDir, subdir+))>

=== consultant-1379/pathfinding-1/symboliclinkcreator/conf/eniq.xml
<!DOCTYPE InterfaceData SYSTEM "eniqmifconfig.dtd">
<InterfaceData>
	<Interface>
		<neType>PM_STATISTICAL_ERBS</neType>
		<maxNumLinks>2000</maxNumLinks>
		<nodeTypeDir>lterbs</nodeTypeDir>
		<subdir>dir1</subdir>
		<subdir>dir2</subdir>
		<subdir>dir3</subdir>
		<subdir>dir4</subdir>
		<subdir>dir5</subdir>
		<subdir>dir6</subdir>
		<subdir>dir7</subdir>
		<subdir>dir8</subdir>
		<subdir>dir9</subdir>
		<subdir>dir10</subdir>
		<subdir>dir11</subdir>
		<subdir>dir12</subdir>
		<subdir>dir13</subdir>
		<subdir>dir14</subdir>
		<subdir>dir15</subdir>
		<subdir>dir16</subdir>
		<subdir>dir17</subdir>
		<subdir>dir18</subdir>
		<subdir>dir19</subdir>
		<subdir>dir20</subdir>
		<subdir>dir21</subdir>
		<subdir>dir22</subdir>
		<subdir>dir23</subdir>
		<subdir>dir24</subdir>
		<subdir>dir25</subdir>
		<subdir>dir26</subdir>
		<subdir>dir27</subdir>
		<subdir>dir28</subdir>
		<subdir>dir29</subdir>
		<subdir>dir30</subdir>
	</Interface>
	<Interface>
		<neType>PM_STATISTICAL_vPP</neType>
		<maxNumLinks>2000</maxNumLinks>
		<nodeTypeDir>vPP/LRAT</nodeTypeDir>
		<subdir>dir1</subdir>
		<subdir>dir2</subdir>
		<subdir>dir3</subdir>
		<subdir>dir4</subdir>
		<subdir>dir5</subdir>
		<subdir>dir6</subdir>
		<subdir>dir7</subdir>
	</Interface>
	<Interface>
		<neType>PM_STATISTICAL_MGW</neType>
		<maxNumLinks>2000</maxNumLinks>
		<nodeTypeDir>mgw</nodeTypeDir>
		<subdir>dir1</subdir>
		<subdir>dir2</subdir>
		<subdir>dir3</subdir>
		<subdir>dir4</subdir>
		<subdir>dir5</subdir>
		<subdir>dir6</subdir>
		<subdir>dir7</subdir>
	</Interface>
	<Interface>
		<neType>PM_STATISTICAL_MGW</neType>
		<maxNumLinks>2000</maxNumLinks>
		<nodeTypeDir>EMRS</nodeTypeDir>
		<subdir>dir1</subdir>
		<subdir>dir2</subdir>
		<subdir>dir3</subdir>
		<subdir>dir4</subdir>
		<subdir>dir5</subdir>
		<subdir>dir6</subdir>
		<subdir>dir7</subdir>
	</Interface>
	<Interface>
		<neType>PM_STATISTICAL_RBS</neType>
		<maxNumLinks>2000</maxNumLinks>
		<nodeTypeDir>rbs</nodeTypeDir>
		<subdir>dir1</subdir>
		<subdir>dir2</subdir>
		<subdir>dir3</subdir>
		<subdir>dir4</subdir>
		<subdir>dir5</subdir>
	</Interface>
	<Interface>
		<neType>PM_STATISTICAL_RNC</neType>
		<maxNumLinks>2000</maxNumLinks>
		<nodeTypeDir>rnc</nodeTypeDir>
		<subdir>dir1</subdir>
		<subdir>dir2</subdir>
		<subdir>dir3</subdir>
		<subdir>dir4</subdir>
		<subdir>dir5</subdir>
	</Interface>
	<Interface>
		<neType>PM_STATISTICAL_RXI</neType>
		<maxNumLinks>2000</maxNumLinks>
		<nodeTypeDir>rxi</nodeTypeDir>
		<subdir>dir1</subdir>
		<subdir>dir2</subdir>
		<subdir>dir3</subdir>
		<subdir>dir4</subdir>
		<subdir>dir5</subdir>
	</Interface>
	<Interface>
		<neType>PM_STATISTICAL_SGSN</neType>
		<maxNumLinks>2000</maxNumLinks>
		<nodeTypeDir>sgsn</nodeTypeDir>
		<subdir>dir1</subdir>
		<subdir>dir2</subdir>
		<subdir>dir3</subdir>
		<subdir>dir4</subdir>
		<subdir>dir5</subdir>
	</Interface>
	<Interface>
		<neType>PM_STATISTICAL_SGSN</neType>
		<maxNumLinks>2000</maxNumLinks>
		<nodeTypeDir>mme</nodeTypeDir>
		<subdir>dir1</subdir>
		<subdir>dir2</subdir>
		<subdir>dir3</subdir>
		<subdir>dir4</subdir>
		<subdir>dir5</subdir>
	</Interface>
	<Interface>
		<neType>PM_STATISTICAL_SGSN</neType>
		<maxNumLinks>2000</maxNumLinks>
		<nodeTypeDir>sgsn-xml-3gpp_32.435</nodeTypeDir>
		<subdir>dir1</subdir>
		<subdir>dir2</subdir>
		<subdir>dir3</subdir>
		<subdir>dir4</subdir>
		<subdir>dir5</subdir>
	</Interface>
	<Interface>
		<neType>PM_STATISTICAL_RadioNode_LTE</neType> 
		<maxNumLinks>2000</maxNumLinks>
		<nodeTypeDir>RadioNode/MIXED</nodeTypeDir>
		<subdir>dir1</subdir>
		<subdir>dir2</subdir>
		<subdir>dir3</subdir>
		<subdir>dir4</subdir>
		<subdir>dir5</subdir>
		<subdir>dir6</subdir>
		<subdir>dir7</subdir>
		<subdir>dir8</subdir>
		<subdir>dir9</subdir>
		<subdir>dir10</subdir>
	</Interface>
	<Interface>
		<neType>PM_STATISTICAL_RadioNode_WCDMA</neType> 
		<maxNumLinks>2000</maxNumLinks>
		<nodeTypeDir>RadioNode/MIXED</nodeTypeDir>
		<subdir>dir1</subdir>
		<subdir>dir2</subdir>
		<subdir>dir3</subdir>
		<subdir>dir4</subdir>
		<subdir>dir5</subdir>
		<subdir>dir6</subdir>
		<subdir>dir7</subdir>
		<subdir>dir8</subdir>
		<subdir>dir9</subdir>
		<subdir>dir10</subdir>
	</Interface>
	<Interface>
		<neType>PM_STATISTICAL_RadioNode_LTE</neType>  
		<maxNumLinks>2000</maxNumLinks>
		<nodeTypeDir>RadioNode/COMMON</nodeTypeDir>
		<subdir>dir1</subdir>
		<subdir>dir2</subdir>
		<subdir>dir3</subdir>
		<subdir>dir4</subdir>
		<subdir>dir5</subdir>
		<subdir>dir6</subdir>
		<subdir>dir7</subdir>
		<subdir>dir8</subdir>
		<subdir>dir9</subdir>
		<subdir>dir10</subdir>
	</Interface>
	<Interface>
		<neType>PM_STATISTICAL_RadioNode_WCDMA</neType>  
		<maxNumLinks>2000</maxNumLinks>
		<nodeTypeDir>RadioNode/COMMON</nodeTypeDir>
		<subdir>dir1</subdir>
		<subdir>dir2</subdir>
		<subdir>dir3</subdir>
		<subdir>dir4</subdir>
		<subdir>dir5</subdir>
		<subdir>dir6</subdir>
		<subdir>dir7</subdir>
		<subdir>dir8</subdir>
		<subdir>dir9</subdir>
		<subdir>dir10</subdir>
	</Interface>
	<Interface>
		<neType>PM_STATISTICAL_RadioNode_WCDMA</neType>
		<maxNumLinks>2000</maxNumLinks>
		<nodeTypeDir>RadioNode/WRAT</nodeTypeDir>
		<subdir>dir1</subdir>
		<subdir>dir2</subdir>
		<subdir>dir3</subdir>
		<subdir>dir4</subdir>
		<subdir>dir5</subdir>
		<subdir>dir6</subdir>
		<subdir>dir7</subdir>
		<subdir>dir8</subdir>
		<subdir>dir9</subdir>
		<subdir>dir10</subdir>
	</Interface>
	<Interface>
		<neType>PM_STATISTICAL_RadioNode_LTE</neType>
		<maxNumLinks>2000</maxNumLinks>
		<nodeTypeDir>RadioNode/LRAT</nodeTypeDir>
		<subdir>dir1</subdir>
		<subdir>dir2</subdir>
		<subdir>dir3</subdir>
		<subdir>dir4</subdir>
		<subdir>dir5</subdir>
		<subdir>dir6</subdir>
		<subdir>dir7</subdir>
		<subdir>dir8</subdir>
		<subdir>dir9</subdir>
		<subdir>dir10</subdir>
		<subdir>dir11</subdir>
		<subdir>dir12</subdir>
		<subdir>dir13</subdir>
		<subdir>dir14</subdir>
		<subdir>dir15</subdir>
		<subdir>dir16</subdir>
		<subdir>dir17</subdir>
		<subdir>dir18</subdir>
		<subdir>dir19</subdir>
		<subdir>dir20</subdir>
		<subdir>dir21</subdir>
		<subdir>dir22</subdir>
		<subdir>dir23</subdir>
		<subdir>dir24</subdir>
		<subdir>dir25</subdir>
		<subdir>dir26</subdir>
		<subdir>dir27</subdir>
		<subdir>dir28</subdir>
		<subdir>dir29</subdir>
		<subdir>dir30</subdir>
	</Interface>
	<Interface>
		<neType>PM_STATISTICAL_MSRBS_V1_LTE</neType>
		<maxNumLinks>2000</maxNumLinks>
		<nodeTypeDir>Msrbs_V1/MIXED</nodeTypeDir>
		<subdir>dir1</subdir>
		<subdir>dir2</subdir>
		<subdir>dir3</subdir>
		<subdir>dir4</subdir>
		<subdir>dir5</subdir>
	</Interface>
	<Interface>
		<neType>PM_STATISTICAL_MSRBS_V1_LTE</neType>
		<maxNumLinks>2000</maxNumLinks>
		<nodeTypeDir>Msrbs_V1/COMMON</nodeTypeDir>
		<subdir>dir1</subdir>
		<subdir>dir2</subdir>
		<subdir>dir3</subdir>
		<subdir>dir4</subdir>
		<subdir>dir5</subdir>
	</Interface>
	<Interface>
		<neType>PM_STATISTICAL_MSRBS_V1_LTE</neType>
		<maxNumLinks>2000</maxNumLinks>
		<nodeTypeDir>Msrbs_V1/LRAT</nodeTypeDir>
		<subdir>dir1</subdir>
		<subdir>dir2</subdir>
		<subdir>dir3</subdir>
		<subdir>dir4</subdir>
		<subdir>dir5</subdir>
	</Interface>
	<Interface>
		<neType>PM_STATISTICAL_MSRBS_V1_LTE</neType>
		<maxNumLinks>2000</maxNumLinks>
		<nodeTypeDir>Msrbs_V1</nodeTypeDir>
		<subdir>dir1</subdir>
		<subdir>dir2</subdir>
		<subdir>dir3</subdir>
		<subdir>dir4</subdir>
		<subdir>dir5</subdir>
	</Interface>
	<Interface>
		<neType>PM_STATISTICAL_MSRBS_V1_WCDMA</neType>
		<maxNumLinks>2000</maxNumLinks>
		<nodeTypeDir>Msrbs_V1/MIXED</nodeTypeDir>
		<subdir>dir1</subdir>
		<subdir>dir2</subdir>
		<subdir>dir3</subdir>
		<subdir>dir4</subdir>
		<subdir>dir5</subdir>
	</Interface>
	<Interface>
		<neType>PM_STATISTICAL_MSRBS_V1_WCDMA</neType>
		<maxNumLinks>2000</maxNumLinks>
		<nodeTypeDir>Msrbs_V1/COMMON</nodeTypeDir>
		<subdir>dir1</subdir>
		<subdir>dir2</subdir>
		<subdir>dir3</subdir>
		<subdir>dir4</subdir>
		<subdir>dir5</subdir>
	</Interface>
	<Interface>
		<neType>PM_STATISTICAL_MSRBS_V1_WCDMA</neType>
		<maxNumLinks>2000</maxNumLinks>
		<nodeTypeDir>wranprbs</nodeTypeDir>
		<subdir>dir1</subdir>
		<subdir>dir2</subdir>
		<subdir>dir3</subdir>
		<subdir>dir4</subdir>
		<subdir>dir5</subdir>
	</Interface>
	<Interface>
		<neType>PM_STATISTICAL_MSRBS_V1_WCDMA</neType>
		<maxNumLinks>2000</maxNumLinks>
		<nodeTypeDir>Msrbs_V1/WRAT</nodeTypeDir>
		<subdir>dir1</subdir>
		<subdir>dir2</subdir>
		<subdir>dir3</subdir>
		<subdir>dir4</subdir>
		<subdir>dir5</subdir>
	</Interface>
	<Interface>
		<neType>PM_STATISTICAL_SAPC</neType>
		<maxNumLinks>2000</maxNumLinks>
		<nodeTypeDir>sapc</nodeTypeDir>
		<subdir>dir1</subdir>
		<subdir>dir2</subdir>
		<subdir>dir3</subdir>
		<subdir>dir4</subdir>
		<subdir>dir5</subdir>
	</Interface>
	<Interface>
		<neType>PM_STATISTICAL_eSAPC</neType>
		<maxNumLinks>2000</maxNumLinks>
		<nodeTypeDir>sapc-ecim</nodeTypeDir>
		<subdir>dir1</subdir>
		<subdir>dir2</subdir>
		<subdir>dir3</subdir>
		<subdir>dir4</subdir>
		<subdir>dir5</subdir>
	</Interface>
	<Interface>
		<neType>PM_STATISTICAL_CSCF</neType> 
		<maxNumLinks>2000</maxNumLinks>
		<nodeTypeDir>ims</nodeTypeDir>
		<subdir>dir1</subdir>
		<subdir>dir2</subdir>
		<subdir>dir3</subdir>
		<subdir>dir4</subdir>
		<subdir>dir5</subdir>
	</Interface>
	<Interface>
		<neType>PM_STATISTICAL_MTAS</neType>
		<maxNumLinks>2000</maxNumLinks>
		<nodeTypeDir>MTAS</nodeTypeDir>
		<subdir>dir1</subdir>
		<subdir>dir2</subdir>
		<subdir>dir3</subdir>
		<subdir>dir4</subdir>
		<subdir>dir5</subdir>
	</Interface>
	<Interface>
		<neType>PM_STATISTICAL_SGSN-MME</neType>
		<maxNumLinks>2000</maxNumLinks>
		<nodeTypeDir>sgsn_mme_cba</nodeTypeDir>
		<subdir>dir1</subdir>
		<subdir>dir2</subdir>
		<subdir>dir3</subdir>
		<subdir>dir4</subdir>
		<subdir>dir5</subdir>
		<subdir>dir6</subdir>
		<subdir>dir7</subdir>
		<subdir>dir8</subdir>
		<subdir>dir9</subdir>
		<subdir>dir10</subdir>
	</Interface>
	<Interface>
		<neType>PM_STATISTICAL_CSCF_CBA</neType>
		<maxNumLinks>2000</maxNumLinks>
		<nodeTypeDir>cscf</nodeTypeDir>
		<subdir>dir1</subdir>
